# Generated by Django 6.0.5 on 2026-05-30 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("BLACK", "Black"),
                            ("WHITE", "White"),
                            ("BLUE", "Blue"),
                            ("RED", "Red"),
                            ("GREEN", "Green"),
                        ],
                        max_length=10,
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "size", "color")},
            },
        ),
    ]
