# Generated by Django 6.0.5 on 2026-05-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В обработке"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
