# Generated by Django 6.0.5 on 2026-05-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productvariant"),
        ("orders", "0005_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.productvariant",
            ),
        ),
    ]
